//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PupilBookEntities : DbContext
    {
        public PupilBookEntities()
            : base("name=PupilBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceSet> AttendanceSet { get; set; }
        public virtual DbSet<InformationsSet> InformationsSet { get; set; }
        public virtual DbSet<ResultsSet> ResultsSet { get; set; }
        public virtual DbSet<SheduleHoursSet> SheduleHoursSet { get; set; }
        public virtual DbSet<SheduleItemSet> SheduleItemSet { get; set; }
        public virtual DbSet<SheduleSet> SheduleSet { get; set; }
        public virtual DbSet<StudentSet> StudentSet { get; set; }
        public virtual DbSet<StudentsNotesSet> StudentsNotesSet { get; set; }
        public virtual DbSet<StudyGroupSet> StudyGroupSet { get; set; }
        public virtual DbSet<StudySubjectSet> StudySubjectSet { get; set; }
        public virtual DbSet<SubjectSubCategorySet> SubjectSubCategorySet { get; set; }
        public virtual DbSet<UserSet> UserSet { get; set; }
        public virtual DbSet<YearSet> YearSet { get; set; }
    }
}
