//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationsSet
    {
        public int Id { get; set; }
        public string InfoForStudent { get; set; }
        public string InfoForParent { get; set; }
        public string Description { get; set; }
        public string Info { get; set; }
        public Nullable<int> StudyGroup_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual StudentSet StudentSet { get; set; }
        public virtual StudyGroupSet StudyGroupSet { get; set; }
    }
}
