//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheduleSet
    {
        public SheduleSet()
        {
            this.SheduleHoursSet = new HashSet<SheduleHoursSet>();
            this.SheduleItemSet = new HashSet<SheduleItemSet>();
        }
    
        public int Id { get; set; }
        public string Period { get; set; }
        public Nullable<bool> EvenWeek { get; set; }
        public int SchoolYear_Id { get; set; }
    
        public virtual ICollection<SheduleHoursSet> SheduleHoursSet { get; set; }
        public virtual YearSet YearSet { get; set; }
        public virtual ICollection<SheduleItemSet> SheduleItemSet { get; set; }
    }
}
