//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSet
    {
        public StudentSet()
        {
            this.AttendanceSet = new HashSet<AttendanceSet>();
            this.InformationsSet = new HashSet<InformationsSet>();
            this.ResultsSet = new HashSet<ResultsSet>();
            this.StudentsNotesSet = new HashSet<StudentsNotesSet>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string QRcodeKeyParent { get; set; }
        public string QRcodeKeyStudent { get; set; }
        public int StudyGroup_Id { get; set; }
        public string ParentsEmail { get; set; }
        public string ParentsPhone { get; set; }
    
        public virtual ICollection<AttendanceSet> AttendanceSet { get; set; }
        public virtual ICollection<InformationsSet> InformationsSet { get; set; }
        public virtual ICollection<ResultsSet> ResultsSet { get; set; }
        public virtual ICollection<StudentsNotesSet> StudentsNotesSet { get; set; }
        public virtual StudyGroupSet StudyGroupSet { get; set; }
    }
}
