//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudySubjectSet
    {
        public StudySubjectSet()
        {
            this.SubjectSubCategorySet = new HashSet<SubjectSubCategorySet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SchoolYear_Id { get; set; }
    
        public virtual YearSet YearSet { get; set; }
        public virtual ICollection<SubjectSubCategorySet> SubjectSubCategorySet { get; set; }
    }
}
