//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsNotesSet
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public int SubjectSubCategory_Id { get; set; }
        public int Student_Id { get; set; }
    
        public virtual StudentSet StudentSet { get; set; }
        public virtual SubjectSubCategorySet SubjectSubCategorySet { get; set; }
    }
}
