//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroupSet
    {
        public StudyGroupSet()
        {
            this.InformationsSet = new HashSet<InformationsSet>();
            this.StudentSet = new HashSet<StudentSet>();
            this.SheduleItemSet = new HashSet<SheduleItemSet>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public int SchoolYear_Id { get; set; }
        public string GroupNameShort { get; set; }
        public string GroupDescription { get; set; }
    
        public virtual ICollection<InformationsSet> InformationsSet { get; set; }
        public virtual ICollection<StudentSet> StudentSet { get; set; }
        public virtual YearSet YearSet { get; set; }
        public virtual ICollection<SheduleItemSet> SheduleItemSet { get; set; }
    }
}
