//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAplicationForTeachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearSet
    {
        public YearSet()
        {
            this.SheduleSet = new HashSet<SheduleSet>();
            this.StudyGroupSet = new HashSet<StudyGroupSet>();
            this.StudySubjectSet = new HashSet<StudySubjectSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool ActualYear { get; set; }
        public string User_Id { get; set; }
    
        public virtual ICollection<SheduleSet> SheduleSet { get; set; }
        public virtual ICollection<StudyGroupSet> StudyGroupSet { get; set; }
        public virtual ICollection<StudySubjectSet> StudySubjectSet { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
