//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakalarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public System.DateTime MissingStart { get; set; }
        public Nullable<System.DateTime> MissingEnd { get; set; }
        public bool Excused { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
