//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakalarka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Year> YearSet { get; set; }
        public virtual DbSet<StudyGroup> StudyGroupSet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<StudySubject> StudySubjectSet { get; set; }
        public virtual DbSet<SubjectSubCategory> SubjectSubCategorySet { get; set; }
        public virtual DbSet<Results> ResultsSet { get; set; }
        public virtual DbSet<StudentsNotes> StudentsNotesSet { get; set; }
        public virtual DbSet<Shedule> SheduleSet { get; set; }
        public virtual DbSet<Attendance> AttendanceSet { get; set; }
        public virtual DbSet<SheduleItem> SheduleItemSet { get; set; }
        public virtual DbSet<SheduleHours> SheduleHoursSet { get; set; }
        public virtual DbSet<Informations> InformationsSet { get; set; }
    }
}
