//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakalarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        public StudyGroup()
        {
            this.Student = new HashSet<Student>();
            this.Informations = new HashSet<Informations>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
    
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Informations> Informations { get; set; }
    }
}
