//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakalarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.SchoolResults = new HashSet<SchoolResults>();
            this.StudentsNotes = new HashSet<StudentsNotes>();
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual StudyGroup StudyGroup { get; set; }
        public virtual ICollection<SchoolResults> SchoolResults { get; set; }
        public virtual ICollection<StudentsNotes> StudentsNotes { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
    }
}
