//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakalarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectSubCategory
    {
        public SubjectSubCategory()
        {
            this.SchoolResults = new HashSet<SchoolResults>();
            this.StudentsNotes = new HashSet<StudentsNotes>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual StudySubject StudySubject { get; set; }
        public virtual ICollection<SchoolResults> SchoolResults { get; set; }
        public virtual ICollection<StudentsNotes> StudentsNotes { get; set; }
        public virtual SheduleItem SheduleItem { get; set; }
    }
}
